name: Bug Report
description: Report a bug in HelixScreen
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the information below so we can reproduce and fix the issue.

  - type: input
    id: version
    attributes:
      label: HelixScreen Version
      description: "Run `helix-screen --version` or check Settings > About"
      placeholder: "e.g. v0.9.10"
    validations:
      required: true

  - type: dropdown
    id: hardware
    attributes:
      label: Hardware Platform
      description: What hardware is HelixScreen running on?
      options:
        - Raspberry Pi 5
        - Raspberry Pi 4
        - Raspberry Pi 3
        - BTT Pi v2
        - BTT CB1
        - Other (describe below)
    validations:
      required: true

  - type: input
    id: screen
    attributes:
      label: Screen / Display
      description: "Screen model and resolution (e.g. BTT HDMI5, Waveshare 7inch, etc.)"
      placeholder: "e.g. BTT HDMI5 (800x480)"
    validations:
      required: true

  - type: input
    id: printer
    attributes:
      label: Printer / Klipper Info
      description: "Printer model, Klipper version, and Moonraker version if relevant"
      placeholder: "e.g. Voron 2.4, Klipper v0.12.x, Moonraker v0.9.x"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect to happen?
      placeholder: "Describe the issue clearly..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Go to '...'
        2. Tap on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: "Run with `helix-screen -vv` and paste relevant output. Wrap in a code block."
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "If applicable, add screenshots. Press 'S' in the UI to capture."
    validations:
      required: false
