name: Feature Request
description: Suggest a new feature or improvement for HelixScreen
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for HelixScreen? We'd love to hear it!

  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: "What problem does this solve? What's frustrating or missing?"
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: "How would you like this to work?"
      placeholder: "It would be great if..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: "Have you tried any workarounds or considered other approaches?"
    validations:
      required: false

  - type: input
    id: printer
    attributes:
      label: Printer / Hardware Setup
      description: "If relevant to the request, what's your setup?"
      placeholder: "e.g. Voron 2.4, Pi 4, BTT HDMI5"
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Mockups
      description: "If you have any visuals to illustrate the idea, attach them here."
    validations:
      required: false
